# Generated by Django 5.1 on 2025-04-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(choices=[(30, 'Option1'), (45, 'Option2'), (60, 'Option3'), (90, 'Option4')], default=60),
        ),
    ]
