# Generated by Django 5.1 on 2025-04-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 min'), (45, '45 min'), (60, '60 min'), (90, '90 min')], default=60),
        ),
    ]
